# Generated by Django 5.2.17 on 2026-10-07 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('node_id', models.CharField(db_index=True, max_length=80)),
                ('packet_type', models.CharField(max_length=80)),
                ('data', models.JSONField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
